name: Update Laravel and create home page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js 16.x
      uses: actions/setup-node@v2
        with:
          node-version: '16.x'

    - name: Check Laravel version and update if necessary
      run: |
        laravel_version=$(php artisan --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        if [ $laravel_version -lt 9 ]; then
          composer require "laravel/framework:^9.0"
        fi

    - name: Check PHP version
      run: |
        php_version=$(php -r 'echo PHP_VERSION_ID;' 2>/dev/null)
        if [ $php_version -lt 80000 ]; then
          echo "PHP version must be at least 8.0"
          exit 1
        fi

    - name: Create home page
      run: |
        echo "<h1>This was made using an action</h1>" > index.html

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update Laravel and create home page"
        add: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
